In [5]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 22.7 MB/s eta 0:00:00m eta 0:00:010:00:01
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.0/462.0 kB 21.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 22.1 MB/s eta 0:00:00m eta 0:00:010:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.4 MB/s eta 0:00:000:00:01
  Created wheel for grpcio: filename=grpcio-1.32.0-cp39-cp39-linux_x86_64.whl size=3436763 sha256=d999f18f5e90bbfde4212a04305e861abcbaff8183e0d561c5292510eeb1f244
  Stored in directory: /home/piai/.cache/pip/wheels/28/95/38/61aa534c5c1a6f5d4af386f1ac4cafa4828c306660e4c861db
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4832 sha256=ceeed6a539882d3acb79d3e02fc2aa5e3fc24996588d63b9582921b1d4db35

  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.3
    Uninstalling typing_extensions-4.6.3:
      Successfully uninstalled typing_extensions-4.6.3
  Attempting uninstall: termcolor
    Found existing installation: termcolor 2.1.0
    Uninstalling termcolor-2.1.0:
      Successfully uninstalled termcolor-2.1.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0
    Uninstalling tensorflow-estimator-2.6.0:
      Successfully uninstalled tensorflow-estimator-2.6.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 2.0
    Uninstalling flatbuffers-2.0:
      Successfully uninstalled flatbuffers-2.0
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      S

In [55]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [35]:
t = [1, 2, 3, 4, 5,6, 7, 8, 9, 10, 11, 12]
tensor = tf.constant(t)

print(tensor)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)


In [36]:
print("shape", tf.shape(tensor))
print("size", tf.size(tensor))
print("rank", tf.rank(tensor))

shape tf.Tensor([12], shape=(1,), dtype=int32)
size tf.Tensor(12, shape=(), dtype=int32)
rank tf.Tensor(1, shape=(), dtype=int32)


In [37]:
def print_tensor(tensor):
    print(tensor)
    print("shape", tf.shape(tensor))
    print("size", tf.size(tensor))
    print("rank", tf.rank(tensor))

In [38]:
tensor2d = tf.reshape(tensor, [3,4])
print_tensor(tensor2d)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
shape tf.Tensor([3 4], shape=(2,), dtype=int32)
size tf.Tensor(12, shape=(), dtype=int32)
rank tf.Tensor(2, shape=(), dtype=int32)


In [39]:
tensor3d = tf.reshape(tensor, [3,2,2])
print_tensor(tensor3d)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)
shape tf.Tensor([3 2 2], shape=(3,), dtype=int32)
size tf.Tensor(12, shape=(), dtype=int32)
rank tf.Tensor(3, shape=(), dtype=int32)


In [53]:
x = tf.constant([1,0,-1,1])
print_tensor(x)

tf.Tensor([ 1  0 -1  1], shape=(4,), dtype=int32)
shape tf.Tensor([4], shape=(1,), dtype=int32)
size tf.Tensor(4, shape=(), dtype=int32)
rank tf.Tensor(1, shape=(), dtype=int32)


In [41]:
tensor3d = tf.reshape(tensor, [1,3,4])
print_tensor(tensor3d)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(1, 3, 4), dtype=int32)
shape tf.Tensor([1 3 4], shape=(3,), dtype=int32)
size tf.Tensor(12, shape=(), dtype=int32)
rank tf.Tensor(3, shape=(), dtype=int32)


In [42]:
tf.matmul(tensor3d,x)

InvalidArgumentError: In[1] ndims must be >= 2: 1 [Op:BatchMatMulV2]

In [43]:
tensor3d = tf.squeeze(tensor3d)
print_tensor(tensor3d)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
shape tf.Tensor([3 4], shape=(2,), dtype=int32)
size tf.Tensor(12, shape=(), dtype=int32)
rank tf.Tensor(2, shape=(), dtype=int32)


In [44]:
x = tf.expand_dims(x, 1)
tf.matmul(tensor3d, x)

# tensor3d 1,3,4 /// x 4,
# tensor3d 3,4 (squeeze) // x 4,1 (expand_dims)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 2],
       [ 6],
       [10]], dtype=int32)>

In [45]:
print(tensor3d@x)

tf.Tensor(
[[ 2]
 [ 6]
 [10]], shape=(3, 1), dtype=int32)


In [48]:
mat = tf.constant([[1.0, 2.0], [3.0, 4.0]])
#[1,2]
#[3,4]
my_sum = tf.reduce_sum(mat)
my_mean = tf.reduce_mean(mat)

print(my_sum)
print(my_mean)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


In [50]:
print(tf.reduce_mean(mat, axis=0))
print(tf.reduce_mean(mat, axis=1))

print(tf.reduce_sum(mat, axis=0))
print(tf.reduce_sum(mat, axis=1))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)
